### ISSUE TITLE
review for v11 protos

### ISSUE THREAD

**Issue by lewispg228** [sparkfun/FT231X_Breakout#4]
1) Is 'Revised by:' and 'reviser name' included? [NO]
comment: Kade didn't want his name on this, that's okay i guess

2) Do all VCC connections use the VCC symbol (oriented upward)? [NO]
comment: 3.3V net off of JP11 should be a supply symbol

3) Does every part have a NAME and VALUE (with proper prefix and no '$')? [NO]
comment: USBAB connector should be a "JP"

4) Are vias tented correctly? [YES]
comment: Yes, but the bstop by the jumpers needs to be scooted over the jumper traces (or removed)

5) Is the LED color standard followed? (red for power, blue for STAT, green for TX, yellow for RX) [NO]
comment: TX LED should be green, RX led should be yellow

6) Are any traces exposed?  [YES]
comment: Strange bstop near jumpers, also mentioned in via/stop check issue

7) Is the designer name included in tDocu? [YES]
comment: jim lidblom is overlapping the designed by text

**Comment by SFE-KADE** [comment]
1.) Yea I don't want my name on this. It's still Patrick's rev.
2.) Fixed
3.) Fixed. In doing this I noticed there was a symbol update that now includes the shielding as a pin connection. In keeping with the Intel standard for EMI mitigation I connected it directly to ground. This tracks with some other designs on the storefront as well.
4.) Fixed (removed)
5.) Since this is a DFM rev only I'm leaving the LED colors as is as to keep this as the same SKU, same BOM, etc. Changes to LED colors can be done when this entire product line is overhauled.
6.) Fixed (removed)
7.) Fixed

**Comment by lewispg228** [comment]
Thanks Kade. It looks like the strange bstop lines are still on there.

**Comment by SFE-KADE** [comment]
Got some of it but not all of it that last teim. Fixed now.

**Comment by lewispg228** [comment]
right on. looks good. thanks.
